### PR TITLE
fix(packages/proxy): `req.signedCookie is not a function`

### PR DESCRIPTION
**Pull request by jesusprubio**
#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Please confirm that your PR fulfills these requirements

- [x] Multiple commits are squashed into one commit.
- [x] The commit message follows [Conventional Commits](https://github.com/IBM/kui/blob/master/CONTRIBUTING.md#conventional-commits), which allows us to autogenerate release notes; e.g. `fix(plugins/plugin-k8s): fixed annoying bugs`
- [x] All npm dependencies are pinned.

### CODE REVIEW

**Comment by starpit** [comment]
Hola @jesusprubio!

A few questions:

1) I think `cookie-parser` should provide the needed functionality. As you can see from this line: https://github.com/kubernetes-sigs/kui/blob/master/packages/proxy/app/app.js#L36 combined with this from the `cookie-parser` [docs](http://expressjs.com/en/resources/middleware/cookie-parser.html):
> if a secret was provided, as the property req.signedCookies.

I would think then that `req.signedCookies` should be defined, as long as `process.env.KUI_PSK_COOKIE_SECRET` is defined?

2) In any case, any new dependences for the express application should be in packages/proxy/app/package.json? At least that is where dependences like `cookie-parser` are specified.

**Comment by starpit** [comment]
Hmm, i think this might just be a bug in the code. I think it should either be `req.signedCookies['mykey']` or `cookieParser.signedCookie('mykey', 'mysecret')`

Whereas the code currently mixes these two with `req.signedCookie('mykey', 'mysecret')`.

**Comment by jesusprubio** [comment]
I'm just working in this last approach. WIll send a PR update when I finish.

**Comment by jesusprubio** [comment]
Easiest solution:

```
const token = process.env.KUI_PSK_COOKIE_SECRET
            ? req.signedCookies[process.env.KUI_PSK_COOKIE]
            : req.cookies[process.env.KUI_PSK_COOKIE]
```

**Comment by jesusprubio** [comment]
The command I used: 
`docker run --rm -p 9080:9080 -e KUI_PROXY_EXTERNAL_PORT=443 -e KUI_USE_HTTP=false -e KUI_PSK_COOKIE=kuipsk -e KUI_PSK=a -e KUI_PSK_COOKIE_SECRET=b kuishell/kui`

And the cookie:

`s:a.y0SLRAxCrIrQhPyKh5XJj1t4AjWcMF6r1X7Nsg4kiJY`

**Comment by starpit** [comment]
Great, thanks! I also think we will need to check for `req.signedCookies` being defined. It may not be, if the user has no signedCookies? Something like:

```typescript
            ? req.signedCookie ? req.signedCookie[process.env.KUI_PSK_COOKIE] : undefined                            
```

**Comment by jesusprubio** [comment]
The `cookie-parser` documentation says the object `req.signedCookies` is attached once the `.use` the middleware with a `secret` (I have manually confirmed it for our codebase). Now, if the cookie we're looking for is not present, we receive `undefined` anyway.

image

So I think this check would be redundant.

**Comment by starpit** [comment]
I just verified that `req.signedCookies` is undefined if the user has no signed cookies.

**Comment by starpit** [comment]
Thanks! 👍 

One last thing: please squash your commits. Thanks!

**Comment by jesusprubio** [comment]
Git problems, send a new PR: https://github.com/kubernetes-sigs/kui/pull/7803/commits/3e664ce38ba5c19ec0ea58309a688e74afaddc46

**Pull request closed without merging**
