### PR TITLE
chore: bump 8_10_x branch to react 17

### LINKED ISSUE #7376: bump 8_10_x branch to react 17
Needed for a product scenario.

### PR DESCRIPTION
**Pull request by starpit**
Fixes #7376

This PR required an update from helm 2.13.0 (in travis tests) to 2.17.0; 2.13.0 no longer seems to be supported.

#### My PR is a:

- [x] 💥 Breaking change
- [ ] 🐛 Bug fix
- [x] 💅 Enhancement
- [ ] 🚀 New feature

#### Please confirm that your PR fulfills these requirements

- [x] Multiple commits are squashed into one commit.
- [x] The commit message follows [Conventional Commits](https://github.com/IBM/kui/blob/master/CONTRIBUTING.md#conventional-commits), which allows us to autogenerate release notes; e.g. `fix(plugins/plugin-k8s): fixed annoying bugs`
- [x] All npm dependencies are pinned.

### CODE REVIEW

**Comment by starpit** [comment]
We have tested this against IBM travis, and all tests passed.

ref: composer/kui/builds/49839260 (build 6359)

**Review by mark-nc — APPROVED** [review]
/lgtm

**Comment by starpit** [comment]
See my comment above, re: IBM travis tests
/approve

**Pull request merged**
