### PR TITLE
*/package.json: Add override for colors@1.40.0

### PR DESCRIPTION
**Pull request by justaugustus**
#### Description of what you did:

ref:
- https://github.com/advisories/GHSA-5rqg-jm4f-cqx7
- https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
- https://twitter.com/bitandbang/status/1478786515660648448
- https://twitter.com/bitandbang/status/1480605181792370693

Signed-off-by: Stephen Augustus <foo@auggie.dev>

#### My PR is a:

- [ ] 💥 Breaking change
- [x] 🐛 Bug fix
- [ ] 💅 Enhancement
- [ ] 🚀 New feature

#### Please confirm that your PR fulfills these requirements

- [x] Multiple commits are squashed into one commit.
- [x] The commit message follows [Conventional Commits](https://github.com/IBM/kui/blob/master/CONTRIBUTING.md#conventional-commits), which allows us to autogenerate release notes; e.g. `fix(plugins/plugin-k8s): fixed annoying bugs`
- [x] All npm dependencies are pinned.

### CODE REVIEW

**Comment by starpit** [comment]
nice, thanks!

**Comment by justaugustus** [comment]
> nice, thanks!

@starpit -- Happy to help! Just sent a rebase :)

**Comment by starpit** [comment]
Thanks! Hmm. i think our github actions tests currently use node 12, which may explain the test failures -- your package-lock.json was generated with a more recent node? I'll look into this more in a bit.

**Comment by starpit** [comment]
howdy! we have just merged in an update to the github actions workflows to use node 16. after you regenerate your package-lock.json, i am hopeful that your PR will go through. thanks!

**Comment by justaugustus** [comment]
> howdy! we have just merged in an update to the github actions workflows to use node 16. after you regenerate your package-lock.json, i am hopeful that your PR will go through. thanks!

@starpit -- Should be all set now!

**Comment by starpit** [comment]
thanks for the PR! 👍

**Pull request merged**
